language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
before_install:
  - mysql -e 'CREATE DATABASE petapp_test;'

# command to run tests
script:
  - git clone https://github.com/Njaya2019/pet_app.git
  - cd pet_app
  - py.test
  - cd -


after_success:
  - coveralls
