language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_install:
  - mysql -e 'CREATE DATABASE petapp_test;'
  - mysql -e 'CREATE DATABASE pet;'
# command to run tests
script:
  - python test_app_db.py
