language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE pet;'
  - mysql -e 'USE pet; CREATE TABLE pets(id INT(100) NOT NULL AUTO_INCREMENT, 
     pet_name VARCHAR(250) NOT NULL, PRIMARY KEY (id))ENGINE=InnoDB;'
  - git clone https://github.com/Njaya2019/pet_app.git
  - cd pet_app 
  - py.test pet_app/test_app_db.py --cov=pet_app
  - cd -

# command to run tests
script:
  - py.test coveralls/test_app_db.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing


after_success:
  - coveralls
