language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE pet;'
  - mysql -e 'USE pet; CREATE TABLE pets(id INT(100) NOT NULL AUTO_INCREMENT, 
     pet_name VARCHAR(250) NOT NULL, PRIMARY KEY (id))ENGINE=InnoDB;'
  - git clone https://github.com/Njaya2019/pet_app.git
  - cd pet_app 
  - cd -

# command to run tests
script:
  - coverage [run]
  - omit =
    # omit anything in a .local directory anywhere
    */.local/*
    # omit everything in /usr
    /usr/*
    # omit this single file
    utils/tirefire.py
  - coverage report -m
  


after_success:
  - coveralls
